@startuml

class Greeting {
    -Languages language
    +Greeting(Languages language)
    +void SayHi()
}

enum Languages {
    English
    Norwegian
    Swedish
    Vietnamese
}

' Relations between classes
Greeting ..> Languages : uses 

note right of Languages
Vi phạm Open-Closed: Phải sửa mã nguồn hiện có 
(lớp Greeting, enum Languages)
khi thêm ngôn ngữ mới
endnote

@enduml